ERROR_CODE_SUCCESS = 0
ERROR_CODE_INVALID_INPUT = 1
ERROR_CODE_FILE_NOT_FOUND = 2
ERROR_CODE_DIR_NOT_FOUND = 3
ERROR_CODE_INVALID_IMAGE = 4
ERROR_CODE_MODEL_LOAD_ERROR = 5
ERROR_CODE_PROCESSING_ERROR = 6
VERSION = "2.0.0"
